// **********************************************************************
//
// Generated by the ORBacus IDL-to-C++ Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.3

#include <OB/CORBAServer.h>
#include <IClientClient_skel.h>

#ifndef OB_INTEGER_VERSION
#   error No ORBacus version defined! Is <OB/CORBA.h> included?
#endif

#ifndef OB_NO_VERSION_CHECK
#   if (OB_INTEGER_VERSION != 4030300L)
#       error ORBacus version mismatch!
#   endif
#endif

//
// IDL:IClientClient/SendFile:1.0
//
void
POA_IClientClient::_OB_op_SendFile(OB::Upcall_ptr _ob_up)
{
    ::DomainData::File _ob_a0;
    ::DomainData::Address _ob_a1;
    OB::InputStreamImpl* _ob_in = _OB_preUnmarshal(_ob_up);
    ::DomainData::File::_OB_unmarshal(_ob_a0, _ob_in);
    ::DomainData::Address::_OB_unmarshal(_ob_a1, _ob_in);
    _OB_postUnmarshal(_ob_up);
    SendFile(_ob_a0, _ob_a1);
    _OB_postinvoke(_ob_up);
    _OB_preMarshal(_ob_up);
    _OB_postMarshal(_ob_up);
}

//
// IDL:IClientClient/CreatePipe:1.0
//
void
POA_IClientClient::_OB_op_CreatePipe(OB::Upcall_ptr _ob_up)
{
    _OB_preUnmarshal(_ob_up);
    _OB_postUnmarshal(_ob_up);
    CreatePipe();
    _OB_postinvoke(_ob_up);
    _OB_preMarshal(_ob_up);
    _OB_postMarshal(_ob_up);
}

//
// IDL:IClientClient/GetFile:1.0
//
void
POA_IClientClient::_OB_op_GetFile(OB::Upcall_ptr _ob_up)
{
    ::DomainData::Address _ob_a0;
    OB::InputStreamImpl* _ob_in = _OB_preUnmarshal(_ob_up);
    ::DomainData::Address::_OB_unmarshal(_ob_a0, _ob_in);
    _OB_postUnmarshal(_ob_up);
    ::DomainData::File_var _ob_r = GetFile(_ob_a0);
    _OB_postinvoke(_ob_up);
    OB::OutputStreamImpl* _ob_out = _OB_preMarshal(_ob_up);
    _ob_r.in()._OB_marshal(_ob_out);
    _OB_postMarshal(_ob_up);
}

//
// IDL:IClientClient:1.0
//
::CORBA::Boolean
POA_IClientClient::_is_a(const char* type)
    throw(::CORBA::SystemException)
{
    const char** _ob_ids = IClientClient::_OB_staticIds();
    for(::CORBA::ULong _ob_i = 0; _ob_ids[_ob_i] != 0; ++_ob_i)
        if(strcmp(type, _ob_ids[_ob_i]) == 0)
            return true;

    return false;
}

::CORBA::RepositoryId
POA_IClientClient::_primary_interface(const PortableServer::ObjectId&,
                                      PortableServer::POA_ptr)
{
    return ::CORBA::string_dup(IClientClient::_OB_staticIds()[0]);
}

IClientClient_ptr
POA_IClientClient::_this()
{
    ::CORBA::Object_var obj = _OB_createReference();
    IClientClient_var result = IClientClient::_narrow(obj);
    return result._retn();
}

OB::DirectStubImpl_ptr
POA_IClientClient::_OB_createDirectStubImpl(PortableServer::POA_ptr poa,
                                            const PortableServer::ObjectId& oid)
{
    return new OBDirectStubImpl_IClientClient(poa, oid, this);
}

void
POA_IClientClient::_OB_dispatch(OB::Upcall_ptr _ob_up)
{
    static const char* _ob_names[] =
    {
        "CreatePipe",
        "GetFile",
        "SendFile"
    };
    static const ::CORBA::ULong _ob_numNames = 3;

    switch(_OB_findOperation(_ob_up, _ob_names, _ob_numNames))
    {
    case 0: // CreatePipe
        _OB_op_CreatePipe(_ob_up);
        return;

    case 1: // GetFile
        _OB_op_GetFile(_ob_up);
        return;

    case 2: // SendFile
        _OB_op_SendFile(_ob_up);
        return;
    }

    _OB_dispatchBase(_ob_up);
}

//
// IDL:IClientClient:1.0
//
OBDirectStubImpl_IClientClient::OBDirectStubImpl_IClientClient(
    PortableServer::POA_ptr poa,
    const PortableServer::ObjectId& oid,
    PortableServer::ServantBase* servant)
#ifdef HAVE_VCPLUSPLUS_BUGS
{
    _ob_initialize(poa, oid, servant);
}
#else
    : OB::DirectStubImpl(poa, oid, servant)
{
}
#endif

//
// IDL:IClientClient/SendFile:1.0
//
void
OBDirectStubImpl_IClientClient::SendFile(const ::DomainData::File& _ob_a0,
                                         const ::DomainData::Address& _ob_a1)
{
    OB::InvocationHandler _ob_handler(this, "SendFile");
    dynamic_cast<POA_IClientClient*>(_ob_servant_) -> SendFile(_ob_a0, _ob_a1);
}

//
// IDL:IClientClient/CreatePipe:1.0
//
void
OBDirectStubImpl_IClientClient::CreatePipe()
{
    OB::InvocationHandler _ob_handler(this, "CreatePipe");
    dynamic_cast<POA_IClientClient*>(_ob_servant_) -> CreatePipe();
}

//
// IDL:IClientClient/GetFile:1.0
//
::DomainData::File*
OBDirectStubImpl_IClientClient::GetFile(const ::DomainData::Address& _ob_a0)
{
    OB::InvocationHandler _ob_handler(this, "GetFile");
    return dynamic_cast<POA_IClientClient*>(_ob_servant_) -> GetFile(_ob_a0);
}
