// **********************************************************************
//
// Generated by the ORBacus IDL-to-C++ Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.3

#include <OB/CORBAServer.h>
#include <ServerInterfaces_skel.h>

#ifndef OB_INTEGER_VERSION
#   error No ORBacus version defined! Is <OB/CORBA.h> included?
#endif

#ifndef OB_NO_VERSION_CHECK
#   if (OB_INTEGER_VERSION != 4030300L)
#       error ORBacus version mismatch!
#   endif
#endif

//
// IDL:DomainData:1.0
//

//
// IDL:ServerInterfaces:1.0
//

//
// IDL:ServerInterfaces/IServerServer/Join:1.0
//
void
POA_ServerInterfaces::IServerServer::_OB_op_Join(OB::Upcall_ptr _ob_up)
{
    _OB_preUnmarshal(_ob_up);
    _OB_postUnmarshal(_ob_up);
    ::ServerInterfaces::AddressesList_var _ob_r = Join();
    _OB_postinvoke(_ob_up);
    OB::OutputStreamImpl* _ob_out = _OB_preMarshal(_ob_up);
    ::CORBA::ULong _ob_len0 = _ob_r.in().length();
    _ob_out -> write_ulong(_ob_len0);
    ::DomainData::Address const * _ob_buf0 = _ob_r.in().get_buffer();
    for(::CORBA::ULong _ob_i0 = 0 ; _ob_i0 < _ob_len0 ; _ob_i0++)
    {
        _ob_buf0[_ob_i0]._OB_marshal(_ob_out);
    }
    _OB_postMarshal(_ob_up);
}

//
// IDL:ServerInterfaces/IServerServer/Unjoin:1.0
//
void
POA_ServerInterfaces::IServerServer::_OB_op_Unjoin(OB::Upcall_ptr _ob_up)
{
    _OB_preUnmarshal(_ob_up);
    _OB_postUnmarshal(_ob_up);
    Unjoin();
    _OB_postinvoke(_ob_up);
    _OB_preMarshal(_ob_up);
    _OB_postMarshal(_ob_up);
}

//
// IDL:ServerInterfaces/IServerServer/AddServer:1.0
//
void
POA_ServerInterfaces::IServerServer::_OB_op_AddServer(OB::Upcall_ptr _ob_up)
{
    ::DomainData::Address _ob_a0;
    OB::InputStreamImpl* _ob_in = _OB_preUnmarshal(_ob_up);
    ::DomainData::Address::_OB_unmarshal(_ob_a0, _ob_in);
    _OB_postUnmarshal(_ob_up);
    AddServer(_ob_a0);
    _OB_postinvoke(_ob_up);
    _OB_preMarshal(_ob_up);
    _OB_postMarshal(_ob_up);
}

//
// IDL:ServerInterfaces/IServerServer/RemoveServer:1.0
//
void
POA_ServerInterfaces::IServerServer::_OB_op_RemoveServer(OB::Upcall_ptr _ob_up)
{
    ::DomainData::Address _ob_a0;
    OB::InputStreamImpl* _ob_in = _OB_preUnmarshal(_ob_up);
    ::DomainData::Address::_OB_unmarshal(_ob_a0, _ob_in);
    _OB_postUnmarshal(_ob_up);
    RemoveServer(_ob_a0);
    _OB_postinvoke(_ob_up);
    _OB_preMarshal(_ob_up);
    _OB_postMarshal(_ob_up);
}

//
// IDL:ServerInterfaces/IServerServer/PassMessage:1.0
//
void
POA_ServerInterfaces::IServerServer::_OB_op_PassMessage(OB::Upcall_ptr _ob_up)
{
    ::DomainData::Message _ob_a0;
    ::DomainData::Address _ob_a1;
    ::DomainData::Address _ob_a2;
    OB::InputStreamImpl* _ob_in = _OB_preUnmarshal(_ob_up);
    ::DomainData::Message::_OB_unmarshal(_ob_a0, _ob_in);
    ::DomainData::Address::_OB_unmarshal(_ob_a1, _ob_in);
    ::DomainData::Address::_OB_unmarshal(_ob_a2, _ob_in);
    _OB_postUnmarshal(_ob_up);
    PassMessage(_ob_a0, _ob_a1, _ob_a2);
    _OB_postinvoke(_ob_up);
    _OB_preMarshal(_ob_up);
    _OB_postMarshal(_ob_up);
}

//
// IDL:ServerInterfaces/IServerServer/PassCreatePipeRequest:1.0
//
void
POA_ServerInterfaces::IServerServer::_OB_op_PassCreatePipeRequest(OB::Upcall_ptr _ob_up)
{
    ::DomainData::Address _ob_a0;
    ::DomainData::Address _ob_a1;
    ::DomainData::Address _ob_a2;
    OB::InputStreamImpl* _ob_in = _OB_preUnmarshal(_ob_up);
    ::DomainData::Address::_OB_unmarshal(_ob_a0, _ob_in);
    ::DomainData::Address::_OB_unmarshal(_ob_a1, _ob_in);
    ::DomainData::Address::_OB_unmarshal(_ob_a2, _ob_in);
    _OB_postUnmarshal(_ob_up);
    PassCreatePipeRequest(_ob_a0, _ob_a1, _ob_a2);
    _OB_postinvoke(_ob_up);
    _OB_preMarshal(_ob_up);
    _OB_postMarshal(_ob_up);
}

//
// IDL:ServerInterfaces/IServerServer/ClientStatusChanged:1.0
//
void
POA_ServerInterfaces::IServerServer::_OB_op_ClientStatusChanged(OB::Upcall_ptr _ob_up)
{
    ::DomainData::Address _ob_a0;
    ::DomainData::Enability _ob_a1;
    OB::InputStreamImpl* _ob_in = _OB_preUnmarshal(_ob_up);
    ::DomainData::Address::_OB_unmarshal(_ob_a0, _ob_in);
    ::DomainData::Enability::_OB_unmarshal(_ob_a1, _ob_in);
    _OB_postUnmarshal(_ob_up);
    ClientStatusChanged(_ob_a0, _ob_a1);
    _OB_postinvoke(_ob_up);
    _OB_preMarshal(_ob_up);
    _OB_postMarshal(_ob_up);
}

//
// IDL:ServerInterfaces/IServerServer:1.0
//
::CORBA::Boolean
POA_ServerInterfaces::IServerServer::_is_a(const char* type)
    throw(::CORBA::SystemException)
{
    const char** _ob_ids = ServerInterfaces::IServerServer::_OB_staticIds();
    for(::CORBA::ULong _ob_i = 0; _ob_ids[_ob_i] != 0; ++_ob_i)
        if(strcmp(type, _ob_ids[_ob_i]) == 0)
            return true;

    return false;
}

::CORBA::RepositoryId
POA_ServerInterfaces::IServerServer::_primary_interface(const PortableServer::ObjectId&,
                                                        PortableServer::POA_ptr)
{
    return ::CORBA::string_dup(ServerInterfaces::IServerServer::_OB_staticIds()[0]);
}

ServerInterfaces::IServerServer_ptr
POA_ServerInterfaces::IServerServer::_this()
{
    ::CORBA::Object_var obj = _OB_createReference();
    ServerInterfaces::IServerServer_var result = ServerInterfaces::IServerServer::_narrow(obj);
    return result._retn();
}

OB::DirectStubImpl_ptr
POA_ServerInterfaces::IServerServer::_OB_createDirectStubImpl(PortableServer::POA_ptr poa,
                                                              const PortableServer::ObjectId& oid)
{
    return new OBDirectStubImpl_ServerInterfaces::IServerServer(poa, oid, this);
}

void
POA_ServerInterfaces::IServerServer::_OB_dispatch(OB::Upcall_ptr _ob_up)
{
    static const char* _ob_names[] =
    {
        "AddServer",
        "ClientStatusChanged",
        "Join",
        "PassCreatePipeRequest",
        "PassMessage",
        "RemoveServer",
        "Unjoin"
    };
    static const ::CORBA::ULong _ob_numNames = 7;

    switch(_OB_findOperation(_ob_up, _ob_names, _ob_numNames))
    {
    case 0: // AddServer
        _OB_op_AddServer(_ob_up);
        return;

    case 1: // ClientStatusChanged
        _OB_op_ClientStatusChanged(_ob_up);
        return;

    case 2: // Join
        _OB_op_Join(_ob_up);
        return;

    case 3: // PassCreatePipeRequest
        _OB_op_PassCreatePipeRequest(_ob_up);
        return;

    case 4: // PassMessage
        _OB_op_PassMessage(_ob_up);
        return;

    case 5: // RemoveServer
        _OB_op_RemoveServer(_ob_up);
        return;

    case 6: // Unjoin
        _OB_op_Unjoin(_ob_up);
        return;
    }

    _OB_dispatchBase(_ob_up);
}

//
// IDL:ServerInterfaces/IServerClient/Connect:1.0
//
void
POA_ServerInterfaces::IServerClient::_OB_op_Connect(OB::Upcall_ptr _ob_up)
{
    ::DomainData::Mode _ob_a0;
    ::DomainData::User _ob_a1;
    OB::InputStreamImpl* _ob_in = _OB_preUnmarshal(_ob_up);
    _ob_a0 = (::DomainData::Mode)_ob_in -> read_ulong();
    ::DomainData::User::_OB_unmarshal(_ob_a1, _ob_in);
    _OB_postUnmarshal(_ob_up);
    ::DomainData::Address_var _ob_r = Connect(_ob_a0, _ob_a1);
    _OB_postinvoke(_ob_up);
    OB::OutputStreamImpl* _ob_out = _OB_preMarshal(_ob_up);
    _ob_r.in()._OB_marshal(_ob_out);
    _OB_postMarshal(_ob_up);
}

//
// IDL:ServerInterfaces/IServerClient/Disconnect:1.0
//
void
POA_ServerInterfaces::IServerClient::_OB_op_Disconnect(OB::Upcall_ptr _ob_up)
{
    _OB_preUnmarshal(_ob_up);
    _OB_postUnmarshal(_ob_up);
    Disconnect();
    _OB_postinvoke(_ob_up);
    _OB_preMarshal(_ob_up);
    _OB_postMarshal(_ob_up);
}

//
// IDL:ServerInterfaces/IServerClient/Register:1.0
//
void
POA_ServerInterfaces::IServerClient::_OB_op_Register(OB::Upcall_ptr _ob_up)
{
    ::DomainData::User _ob_a0;
    OB::InputStreamImpl* _ob_in = _OB_preUnmarshal(_ob_up);
    ::DomainData::User::_OB_unmarshal(_ob_a0, _ob_in);
    _OB_postUnmarshal(_ob_up);
    ::DomainData::User_var _ob_r = Register(_ob_a0);
    _OB_postinvoke(_ob_up);
    OB::OutputStreamImpl* _ob_out = _OB_preMarshal(_ob_up);
    _ob_r.in()._OB_marshal(_ob_out);
    _OB_postMarshal(_ob_up);
}

//
// IDL:ServerInterfaces/IServerClient/SendMessage:1.0
//
void
POA_ServerInterfaces::IServerClient::_OB_op_SendMessage(OB::Upcall_ptr _ob_up)
{
    ::DomainData::Address _ob_a0;
    ::DomainData::Message _ob_a1;
    OB::InputStreamImpl* _ob_in = _OB_preUnmarshal(_ob_up);
    ::DomainData::Address::_OB_unmarshal(_ob_a0, _ob_in);
    ::DomainData::Message::_OB_unmarshal(_ob_a1, _ob_in);
    _OB_postUnmarshal(_ob_up);
    SendMessage(_ob_a0, _ob_a1);
    _OB_postinvoke(_ob_up);
    _OB_preMarshal(_ob_up);
    _OB_postMarshal(_ob_up);
}

//
// IDL:ServerInterfaces/IServerClient/CheckClientStatus:1.0
//
void
POA_ServerInterfaces::IServerClient::_OB_op_CheckClientStatus(OB::Upcall_ptr _ob_up)
{
    ::DomainData::Address _ob_a0;
    OB::InputStreamImpl* _ob_in = _OB_preUnmarshal(_ob_up);
    ::DomainData::Address::_OB_unmarshal(_ob_a0, _ob_in);
    _OB_postUnmarshal(_ob_up);
    ::DomainData::Enability _ob_r = CheckClientStatus(_ob_a0);
    _OB_postinvoke(_ob_up);
    OB::OutputStreamImpl* _ob_out = _OB_preMarshal(_ob_up);
    _ob_r._OB_marshal(_ob_out);
    _OB_postMarshal(_ob_up);
}

//
// IDL:ServerInterfaces/IServerClient/GetPipeHolder:1.0
//
void
POA_ServerInterfaces::IServerClient::_OB_op_GetPipeHolder(OB::Upcall_ptr _ob_up)
{
    ::DomainData::Address _ob_a0;
    OB::InputStreamImpl* _ob_in = _OB_preUnmarshal(_ob_up);
    ::DomainData::Address::_OB_unmarshal(_ob_a0, _ob_in);
    _OB_postUnmarshal(_ob_up);
    ::DomainData::Address_var _ob_r = GetPipeHolder(_ob_a0);
    _OB_postinvoke(_ob_up);
    OB::OutputStreamImpl* _ob_out = _OB_preMarshal(_ob_up);
    _ob_r.in()._OB_marshal(_ob_out);
    _OB_postMarshal(_ob_up);
}

//
// IDL:ServerInterfaces/IServerClient:1.0
//
::CORBA::Boolean
POA_ServerInterfaces::IServerClient::_is_a(const char* type)
    throw(::CORBA::SystemException)
{
    const char** _ob_ids = ServerInterfaces::IServerClient::_OB_staticIds();
    for(::CORBA::ULong _ob_i = 0; _ob_ids[_ob_i] != 0; ++_ob_i)
        if(strcmp(type, _ob_ids[_ob_i]) == 0)
            return true;

    return false;
}

::CORBA::RepositoryId
POA_ServerInterfaces::IServerClient::_primary_interface(const PortableServer::ObjectId&,
                                                        PortableServer::POA_ptr)
{
    return ::CORBA::string_dup(ServerInterfaces::IServerClient::_OB_staticIds()[0]);
}

ServerInterfaces::IServerClient_ptr
POA_ServerInterfaces::IServerClient::_this()
{
    ::CORBA::Object_var obj = _OB_createReference();
    ServerInterfaces::IServerClient_var result = ServerInterfaces::IServerClient::_narrow(obj);
    return result._retn();
}

OB::DirectStubImpl_ptr
POA_ServerInterfaces::IServerClient::_OB_createDirectStubImpl(PortableServer::POA_ptr poa,
                                                              const PortableServer::ObjectId& oid)
{
    return new OBDirectStubImpl_ServerInterfaces::IServerClient(poa, oid, this);
}

void
POA_ServerInterfaces::IServerClient::_OB_dispatch(OB::Upcall_ptr _ob_up)
{
    static const char* _ob_names[] =
    {
        "CheckClientStatus",
        "Connect",
        "Disconnect",
        "GetPipeHolder",
        "Register",
        "SendMessage"
    };
    static const ::CORBA::ULong _ob_numNames = 6;

    switch(_OB_findOperation(_ob_up, _ob_names, _ob_numNames))
    {
    case 0: // CheckClientStatus
        _OB_op_CheckClientStatus(_ob_up);
        return;

    case 1: // Connect
        _OB_op_Connect(_ob_up);
        return;

    case 2: // Disconnect
        _OB_op_Disconnect(_ob_up);
        return;

    case 3: // GetPipeHolder
        _OB_op_GetPipeHolder(_ob_up);
        return;

    case 4: // Register
        _OB_op_Register(_ob_up);
        return;

    case 5: // SendMessage
        _OB_op_SendMessage(_ob_up);
        return;
    }

    _OB_dispatchBase(_ob_up);
}

//
// IDL:ServerInterfaces/IServerServer:1.0
//
OBDirectStubImpl_ServerInterfaces::IServerServer::IServerServer(
    PortableServer::POA_ptr poa,
    const PortableServer::ObjectId& oid,
    PortableServer::ServantBase* servant)
#ifdef HAVE_VCPLUSPLUS_BUGS
{
    _ob_initialize(poa, oid, servant);
}
#else
    : OB::DirectStubImpl(poa, oid, servant)
{
}
#endif

//
// IDL:ServerInterfaces/IServerServer/Join:1.0
//
::ServerInterfaces::AddressesList*
OBDirectStubImpl_ServerInterfaces::IServerServer::Join()
{
    OB::InvocationHandler _ob_handler(this, "Join");
    return dynamic_cast<POA_ServerInterfaces::IServerServer*>(_ob_servant_) -> Join();
}

//
// IDL:ServerInterfaces/IServerServer/Unjoin:1.0
//
void
OBDirectStubImpl_ServerInterfaces::IServerServer::Unjoin()
{
    OB::InvocationHandler _ob_handler(this, "Unjoin");
    dynamic_cast<POA_ServerInterfaces::IServerServer*>(_ob_servant_) -> Unjoin();
}

//
// IDL:ServerInterfaces/IServerServer/AddServer:1.0
//
void
OBDirectStubImpl_ServerInterfaces::IServerServer::AddServer(const ::DomainData::Address& _ob_a0)
{
    OB::InvocationHandler _ob_handler(this, "AddServer");
    dynamic_cast<POA_ServerInterfaces::IServerServer*>(_ob_servant_) -> AddServer(_ob_a0);
}

//
// IDL:ServerInterfaces/IServerServer/RemoveServer:1.0
//
void
OBDirectStubImpl_ServerInterfaces::IServerServer::RemoveServer(const ::DomainData::Address& _ob_a0)
{
    OB::InvocationHandler _ob_handler(this, "RemoveServer");
    dynamic_cast<POA_ServerInterfaces::IServerServer*>(_ob_servant_) -> RemoveServer(_ob_a0);
}

//
// IDL:ServerInterfaces/IServerServer/PassMessage:1.0
//
void
OBDirectStubImpl_ServerInterfaces::IServerServer::PassMessage(const ::DomainData::Message& _ob_a0,
                                                              const ::DomainData::Address& _ob_a1,
                                                              const ::DomainData::Address& _ob_a2)
{
    OB::InvocationHandler _ob_handler(this, "PassMessage");
    dynamic_cast<POA_ServerInterfaces::IServerServer*>(_ob_servant_) -> PassMessage(_ob_a0, _ob_a1, _ob_a2);
}

//
// IDL:ServerInterfaces/IServerServer/PassCreatePipeRequest:1.0
//
void
OBDirectStubImpl_ServerInterfaces::IServerServer::PassCreatePipeRequest(const ::DomainData::Address& _ob_a0,
                                                                        const ::DomainData::Address& _ob_a1,
                                                                        const ::DomainData::Address& _ob_a2)
{
    OB::InvocationHandler _ob_handler(this, "PassCreatePipeRequest");
    dynamic_cast<POA_ServerInterfaces::IServerServer*>(_ob_servant_) -> PassCreatePipeRequest(_ob_a0, _ob_a1, _ob_a2);
}

//
// IDL:ServerInterfaces/IServerServer/ClientStatusChanged:1.0
//
void
OBDirectStubImpl_ServerInterfaces::IServerServer::ClientStatusChanged(const ::DomainData::Address& _ob_a0,
                                                                      const ::DomainData::Enability& _ob_a1)
{
    OB::InvocationHandler _ob_handler(this, "ClientStatusChanged");
    dynamic_cast<POA_ServerInterfaces::IServerServer*>(_ob_servant_) -> ClientStatusChanged(_ob_a0, _ob_a1);
}

//
// IDL:ServerInterfaces/IServerClient:1.0
//
OBDirectStubImpl_ServerInterfaces::IServerClient::IServerClient(
    PortableServer::POA_ptr poa,
    const PortableServer::ObjectId& oid,
    PortableServer::ServantBase* servant)
#ifdef HAVE_VCPLUSPLUS_BUGS
{
    _ob_initialize(poa, oid, servant);
}
#else
    : OB::DirectStubImpl(poa, oid, servant)
{
}
#endif

//
// IDL:ServerInterfaces/IServerClient/Connect:1.0
//
::DomainData::Address*
OBDirectStubImpl_ServerInterfaces::IServerClient::Connect(::DomainData::Mode _ob_a0,
                                                          const ::DomainData::User& _ob_a1)
{
    OB::InvocationHandler _ob_handler(this, "Connect");
    return dynamic_cast<POA_ServerInterfaces::IServerClient*>(_ob_servant_) -> Connect(_ob_a0, _ob_a1);
}

//
// IDL:ServerInterfaces/IServerClient/Disconnect:1.0
//
void
OBDirectStubImpl_ServerInterfaces::IServerClient::Disconnect()
{
    OB::InvocationHandler _ob_handler(this, "Disconnect");
    dynamic_cast<POA_ServerInterfaces::IServerClient*>(_ob_servant_) -> Disconnect();
}

//
// IDL:ServerInterfaces/IServerClient/Register:1.0
//
::DomainData::User*
OBDirectStubImpl_ServerInterfaces::IServerClient::Register(const ::DomainData::User& _ob_a0)
{
    OB::InvocationHandler _ob_handler(this, "Register");
    return dynamic_cast<POA_ServerInterfaces::IServerClient*>(_ob_servant_) -> Register(_ob_a0);
}

//
// IDL:ServerInterfaces/IServerClient/SendMessage:1.0
//
void
OBDirectStubImpl_ServerInterfaces::IServerClient::SendMessage(const ::DomainData::Address& _ob_a0,
                                                              const ::DomainData::Message& _ob_a1)
{
    OB::InvocationHandler _ob_handler(this, "SendMessage");
    dynamic_cast<POA_ServerInterfaces::IServerClient*>(_ob_servant_) -> SendMessage(_ob_a0, _ob_a1);
}

//
// IDL:ServerInterfaces/IServerClient/CheckClientStatus:1.0
//
::DomainData::Enability
OBDirectStubImpl_ServerInterfaces::IServerClient::CheckClientStatus(const ::DomainData::Address& _ob_a0)
{
    OB::InvocationHandler _ob_handler(this, "CheckClientStatus");
    return dynamic_cast<POA_ServerInterfaces::IServerClient*>(_ob_servant_) -> CheckClientStatus(_ob_a0);
}

//
// IDL:ServerInterfaces/IServerClient/GetPipeHolder:1.0
//
::DomainData::Address*
OBDirectStubImpl_ServerInterfaces::IServerClient::GetPipeHolder(const ::DomainData::Address& _ob_a0)
{
    OB::InvocationHandler _ob_handler(this, "GetPipeHolder");
    return dynamic_cast<POA_ServerInterfaces::IServerClient*>(_ob_servant_) -> GetPipeHolder(_ob_a0);
}
