// **********************************************************************
//
// Generated by the ORBacus IDL-to-C++ Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.3

#include <OB/CORBAClient.h>
#include <IServerClient.h>

#ifndef OB_INTEGER_VERSION
#   error No ORBacus version defined! Is <OB/CORBA.h> included?
#endif

#ifndef OB_NO_VERSION_CHECK
#   if (OB_INTEGER_VERSION != 4030300L)
#       error ORBacus version mismatch!
#   endif
#endif

::OB::TypeCodeConst _tc_IServerClient(
"017970650e000000320000000102917c1600000049444c3a49536572766572436c69656e743a3"
"12e300063000e00000049536572766572436c69656e7400"
);

//
// IDL:IServerClient:1.0
//
const char* IServerClient::ids_[] =
{
    "IDL:IServerClient:1.0",
    0
};

void
OBDuplicate(IServerClient_ptr p)
{
    if(p)
        p -> _add_ref();
}

void
OBRelease(IServerClient_ptr p)
{
    if(p)
        p -> _remove_ref();
}

IServerClient_ptr
IServerClient::_narrow(::CORBA::Object_ptr p)
{
    if(!::CORBA::is_nil(p))
    {
        IServerClient_ptr v = 
            dynamic_cast< IServerClient_ptr >(p);
        if(v)
            return _duplicate(v);

        if(p -> _is_a(ids_[0]))
        {
            OBProxy_IServerClient* val = new OBProxy_IServerClient;
            val -> _OB_copyFrom(p);
            return val;
        }
    }

    return _nil();
}

IServerClient_ptr
IServerClient::_narrow(::CORBA::AbstractBase_ptr p)
{
    if(!::CORBA::is_nil(p))
    {
        IServerClient_ptr v =
            dynamic_cast< IServerClient_ptr >(p);
        if(v)
            return _duplicate(v);

        ::CORBA::Object_var obj = p -> _to_object();
        return _narrow(obj);
    }
    return _nil();
}

IServerClient_ptr
IServerClient::_unchecked_narrow(::CORBA::Object_ptr p)
{
    if(!::CORBA::is_nil(p))
    {
        IServerClient_ptr v =
            dynamic_cast< IServerClient_ptr >(p);
        if(v)
            return _duplicate(v);

        OBProxy_IServerClient* val = new OBProxy_IServerClient;
        val -> _OB_copyFrom(p);
        return val;
    }

    return _nil();
}

IServerClient_ptr
IServerClient::_unchecked_narrow(::CORBA::AbstractBase_ptr p)
{
    if(!::CORBA::is_nil(p))
    {
        ::CORBA::Object_var obj = p -> _to_object();
        return _unchecked_narrow(obj);
    }
    return _nil();
}

const char**
IServerClient::_OB_staticIds()
{
    return ids_;
}

void
OBMarshal(IServerClient_ptr _ob_v, OB::OutputStreamImpl* _ob_out)
{
    _ob_out -> write_Object(_ob_v);
}

void
OBUnmarshal(IServerClient_ptr& _ob_v, OB::InputStreamImpl* _ob_in)
{
    IServerClient_var old = _ob_v;
    ::CORBA::Object_var p = _ob_in -> read_Object();

    if(!::CORBA::is_nil(p))
    {
        OBProxy_IServerClient* _ob_obj = new OBProxy_IServerClient;
        _ob_obj -> _OB_copyFrom(p);
        _ob_v = _ob_obj;
    }
    else
        _ob_v = IServerClient::_nil();
}

void
operator<<=(::CORBA::Any& any, IServerClient_ptr* v)
{
    any.replace(_tc_IServerClient, (::CORBA::Object_ptr)*v, true);
}

void
operator<<=(::CORBA::Any& any, IServerClient_ptr v)
{
    IServerClient_ptr val = IServerClient::_duplicate(v);
    any <<= &val;
}

::CORBA::Boolean
operator>>=(const ::CORBA::Any& any, IServerClient_ptr& v)
{
    if(any.check_type(_tc_IServerClient))
    {
        ::CORBA::Object_ptr val = (::CORBA::Object_ptr)any.value();

        if(!::CORBA::is_nil(val))
        {
            if(!(v = dynamic_cast< IServerClient_ptr >(val)))
            {
                OBProxy_IServerClient* obj = new OBProxy_IServerClient;
                obj -> _OB_copyFrom(val);
                v = obj;
                (::CORBA::Any&)any <<= &v;
            }
        }
        else
            v = IServerClient::_nil();

        return true;
    }
    else
        return false;
}

//
// IDL:IServerClient:1.0
//
OB::MarshalStubImpl_ptr
OBProxy_IServerClient::_OB_createMarshalStubImpl()
{
    return new OBMarshalStubImpl_IServerClient;
}

const char**
OBProxy_IServerClient::_OB_ids() const
{
    return ::IServerClient::ids_;
}

//
// IDL:IServerClient/Connect:1.0
//
::DomainData::Address*
OBProxy_IServerClient::Connect(const ::DomainData::Address& _ob_a0,
                               ::DomainData::Mode _ob_a1,
                               const ::DomainData::User& _ob_a2)
{
    ::CORBA::ULong _ob_retry = 0, _ob_hop = 0;
    while(true)
    {
        try
        {
            OB::StubImplBase_var _ob_stubImplBase = _OB_getStubImpl();
            OBStubImpl_IServerClient_ptr _ob_stubImpl = 
                dynamic_cast< OBStubImpl_IServerClient_ptr>(_ob_stubImplBase.in());
            return _ob_stubImpl -> Connect(_ob_a0, _ob_a1, _ob_a2);
        }
        catch(const OB::ExceptionBase& _ob_ex)
        {
            _OB_handleException(_ob_ex, _ob_retry, _ob_hop);
        }
    }
}

//
// IDL:IServerClient/Disconnect:1.0
//
void
OBProxy_IServerClient::Disconnect(const ::DomainData::User& _ob_a0)
{
    ::CORBA::ULong _ob_retry = 0, _ob_hop = 0;
    while(true)
    {
        try
        {
            OB::StubImplBase_var _ob_stubImplBase = _OB_getStubImpl();
            OBStubImpl_IServerClient_ptr _ob_stubImpl = 
                dynamic_cast< OBStubImpl_IServerClient_ptr>(_ob_stubImplBase.in());
            _ob_stubImpl -> Disconnect(_ob_a0);
            return;
        }
        catch(const OB::ExceptionBase& _ob_ex)
        {
            _OB_handleException(_ob_ex, _ob_retry, _ob_hop);
        }
    }
}

//
// IDL:IServerClient/Register:1.0
//
::DomainData::User*
OBProxy_IServerClient::Register(const ::DomainData::User& _ob_a0)
{
    ::CORBA::ULong _ob_retry = 0, _ob_hop = 0;
    while(true)
    {
        try
        {
            OB::StubImplBase_var _ob_stubImplBase = _OB_getStubImpl();
            OBStubImpl_IServerClient_ptr _ob_stubImpl = 
                dynamic_cast< OBStubImpl_IServerClient_ptr>(_ob_stubImplBase.in());
            return _ob_stubImpl -> Register(_ob_a0);
        }
        catch(const OB::ExceptionBase& _ob_ex)
        {
            _OB_handleException(_ob_ex, _ob_retry, _ob_hop);
        }
    }
}

//
// IDL:IServerClient/SendMessage:1.0
//
void
OBProxy_IServerClient::SendMessage(const ::DomainData::Address& _ob_a0,
                                   const ::DomainData::User& _ob_a1,
                                   const ::DomainData::Message& _ob_a2)
{
    ::CORBA::ULong _ob_retry = 0, _ob_hop = 0;
    while(true)
    {
        try
        {
            OB::StubImplBase_var _ob_stubImplBase = _OB_getStubImpl();
            OBStubImpl_IServerClient_ptr _ob_stubImpl = 
                dynamic_cast< OBStubImpl_IServerClient_ptr>(_ob_stubImplBase.in());
            _ob_stubImpl -> SendMessage(_ob_a0, _ob_a1, _ob_a2);
            return;
        }
        catch(const OB::ExceptionBase& _ob_ex)
        {
            _OB_handleException(_ob_ex, _ob_retry, _ob_hop);
        }
    }
}

//
// IDL:IServerClient/CheckClientStatus:1.0
//
::DomainData::Enability
OBProxy_IServerClient::CheckClientStatus(const ::DomainData::Address& _ob_a0)
{
    ::CORBA::ULong _ob_retry = 0, _ob_hop = 0;
    while(true)
    {
        try
        {
            OB::StubImplBase_var _ob_stubImplBase = _OB_getStubImpl();
            OBStubImpl_IServerClient_ptr _ob_stubImpl = 
                dynamic_cast< OBStubImpl_IServerClient_ptr>(_ob_stubImplBase.in());
            return _ob_stubImpl -> CheckClientStatus(_ob_a0);
        }
        catch(const OB::ExceptionBase& _ob_ex)
        {
            _OB_handleException(_ob_ex, _ob_retry, _ob_hop);
        }
    }
}

//
// IDL:IServerClient/GetPipeHolder:1.0
//
::DomainData::Address*
OBProxy_IServerClient::GetPipeHolder(const ::DomainData::Address& _ob_a0)
{
    ::CORBA::ULong _ob_retry = 0, _ob_hop = 0;
    while(true)
    {
        try
        {
            OB::StubImplBase_var _ob_stubImplBase = _OB_getStubImpl();
            OBStubImpl_IServerClient_ptr _ob_stubImpl = 
                dynamic_cast< OBStubImpl_IServerClient_ptr>(_ob_stubImplBase.in());
            return _ob_stubImpl -> GetPipeHolder(_ob_a0);
        }
        catch(const OB::ExceptionBase& _ob_ex)
        {
            _OB_handleException(_ob_ex, _ob_retry, _ob_hop);
        }
    }
}

//
// IDL:IServerClient:1.0
//
void
OBDuplicate(OBStubImpl_IServerClient_ptr p)
{
    if(p)
        p -> _OB_incRef();
}

void
OBRelease(OBStubImpl_IServerClient_ptr p)
{
    if(p)
        p -> _OB_decRef();
}

//
// IDL:IServerClient/Connect:1.0
//
::DomainData::Address*
OBMarshalStubImpl_IServerClient::Connect(const ::DomainData::Address& _ob_a0,
                                         ::DomainData::Mode _ob_a1,
                                         const ::DomainData::User& _ob_a2)
{
    while(true)
    {
        OB::Downcall_var _ob_down = _OB_createDowncall("Connect", true);
        try
        {
            OB::OutputStreamImpl* _ob_out = _OB_preMarshal(_ob_down);
            try
            {
                _ob_a0._OB_marshal(_ob_out);
                _ob_out -> write_ulong((::CORBA::ULong)_ob_a1);
                _ob_a2._OB_marshal(_ob_out);
            }
            catch(const ::CORBA::SystemException& _ob_ex)
            {
                _OB_marshalEx(_ob_down, _ob_ex);
            }
            _OB_postMarshal(_ob_down);
            _OB_request(_ob_down);
            bool _ob_uex;
            OB::InputStreamImpl* _ob_in = _OB_preUnmarshal(_ob_down, _ob_uex);
            if(_ob_uex)
            {
                _OB_postUnmarshal(_ob_down);
            }
            else
            {
                ::DomainData::Address_var _ob_r;
                try
                {
                    _ob_r = new ::DomainData::Address;
                    ::DomainData::Address::_OB_unmarshal(_ob_r.inout(), _ob_in);
                }
                catch(const ::CORBA::SystemException& _ob_ex)
                {
                    _OB_unmarshalEx(_ob_down, _ob_ex);
                }
                _OB_postUnmarshal(_ob_down);
                return _ob_r._retn();
            }
        }
        catch(const OB::FailureException& _ob_ex)
        {
            _OB_handleFailureException(_ob_down, _ob_ex);
        }
    }
}

//
// IDL:IServerClient/Disconnect:1.0
//
void
OBMarshalStubImpl_IServerClient::Disconnect(const ::DomainData::User& _ob_a0)
{
    while(true)
    {
        OB::Downcall_var _ob_down = _OB_createDowncall("Disconnect", true);
        try
        {
            OB::OutputStreamImpl* _ob_out = _OB_preMarshal(_ob_down);
            try
            {
                _ob_a0._OB_marshal(_ob_out);
            }
            catch(const ::CORBA::SystemException& _ob_ex)
            {
                _OB_marshalEx(_ob_down, _ob_ex);
            }
            _OB_postMarshal(_ob_down);
            _OB_request(_ob_down);
            _OB_preUnmarshal(_ob_down);
            _OB_postUnmarshal(_ob_down);
            return;
        }
        catch(const OB::FailureException& _ob_ex)
        {
            _OB_handleFailureException(_ob_down, _ob_ex);
        }
    }
}

//
// IDL:IServerClient/Register:1.0
//
::DomainData::User*
OBMarshalStubImpl_IServerClient::Register(const ::DomainData::User& _ob_a0)
{
    while(true)
    {
        OB::Downcall_var _ob_down = _OB_createDowncall("Register", true);
        try
        {
            OB::OutputStreamImpl* _ob_out = _OB_preMarshal(_ob_down);
            try
            {
                _ob_a0._OB_marshal(_ob_out);
            }
            catch(const ::CORBA::SystemException& _ob_ex)
            {
                _OB_marshalEx(_ob_down, _ob_ex);
            }
            _OB_postMarshal(_ob_down);
            _OB_request(_ob_down);
            bool _ob_uex;
            OB::InputStreamImpl* _ob_in = _OB_preUnmarshal(_ob_down, _ob_uex);
            if(_ob_uex)
            {
                _OB_postUnmarshal(_ob_down);
            }
            else
            {
                ::DomainData::User_var _ob_r;
                try
                {
                    _ob_r = new ::DomainData::User;
                    ::DomainData::User::_OB_unmarshal(_ob_r.inout(), _ob_in);
                }
                catch(const ::CORBA::SystemException& _ob_ex)
                {
                    _OB_unmarshalEx(_ob_down, _ob_ex);
                }
                _OB_postUnmarshal(_ob_down);
                return _ob_r._retn();
            }
        }
        catch(const OB::FailureException& _ob_ex)
        {
            _OB_handleFailureException(_ob_down, _ob_ex);
        }
    }
}

//
// IDL:IServerClient/SendMessage:1.0
//
void
OBMarshalStubImpl_IServerClient::SendMessage(const ::DomainData::Address& _ob_a0,
                                             const ::DomainData::User& _ob_a1,
                                             const ::DomainData::Message& _ob_a2)
{
    while(true)
    {
        OB::Downcall_var _ob_down = _OB_createDowncall("SendMessage", true);
        try
        {
            OB::OutputStreamImpl* _ob_out = _OB_preMarshal(_ob_down);
            try
            {
                _ob_a0._OB_marshal(_ob_out);
                _ob_a1._OB_marshal(_ob_out);
                _ob_a2._OB_marshal(_ob_out);
            }
            catch(const ::CORBA::SystemException& _ob_ex)
            {
                _OB_marshalEx(_ob_down, _ob_ex);
            }
            _OB_postMarshal(_ob_down);
            _OB_request(_ob_down);
            _OB_preUnmarshal(_ob_down);
            _OB_postUnmarshal(_ob_down);
            return;
        }
        catch(const OB::FailureException& _ob_ex)
        {
            _OB_handleFailureException(_ob_down, _ob_ex);
        }
    }
}

//
// IDL:IServerClient/CheckClientStatus:1.0
//
::DomainData::Enability
OBMarshalStubImpl_IServerClient::CheckClientStatus(const ::DomainData::Address& _ob_a0)
{
    while(true)
    {
        OB::Downcall_var _ob_down = _OB_createDowncall("CheckClientStatus", true);
        try
        {
            OB::OutputStreamImpl* _ob_out = _OB_preMarshal(_ob_down);
            try
            {
                _ob_a0._OB_marshal(_ob_out);
            }
            catch(const ::CORBA::SystemException& _ob_ex)
            {
                _OB_marshalEx(_ob_down, _ob_ex);
            }
            _OB_postMarshal(_ob_down);
            _OB_request(_ob_down);
            bool _ob_uex;
            OB::InputStreamImpl* _ob_in = _OB_preUnmarshal(_ob_down, _ob_uex);
            if(_ob_uex)
            {
                _OB_postUnmarshal(_ob_down);
            }
            else
            {
                ::DomainData::Enability _ob_r;
                try
                {
                    ::DomainData::Enability::_OB_unmarshal(_ob_r, _ob_in);
                }
                catch(const ::CORBA::SystemException& _ob_ex)
                {
                    _OB_unmarshalEx(_ob_down, _ob_ex);
                }
                _OB_postUnmarshal(_ob_down);
                return _ob_r;
            }
        }
        catch(const OB::FailureException& _ob_ex)
        {
            _OB_handleFailureException(_ob_down, _ob_ex);
        }
    }
}

//
// IDL:IServerClient/GetPipeHolder:1.0
//
::DomainData::Address*
OBMarshalStubImpl_IServerClient::GetPipeHolder(const ::DomainData::Address& _ob_a0)
{
    while(true)
    {
        OB::Downcall_var _ob_down = _OB_createDowncall("GetPipeHolder", true);
        try
        {
            OB::OutputStreamImpl* _ob_out = _OB_preMarshal(_ob_down);
            try
            {
                _ob_a0._OB_marshal(_ob_out);
            }
            catch(const ::CORBA::SystemException& _ob_ex)
            {
                _OB_marshalEx(_ob_down, _ob_ex);
            }
            _OB_postMarshal(_ob_down);
            _OB_request(_ob_down);
            bool _ob_uex;
            OB::InputStreamImpl* _ob_in = _OB_preUnmarshal(_ob_down, _ob_uex);
            if(_ob_uex)
            {
                _OB_postUnmarshal(_ob_down);
            }
            else
            {
                ::DomainData::Address_var _ob_r;
                try
                {
                    _ob_r = new ::DomainData::Address;
                    ::DomainData::Address::_OB_unmarshal(_ob_r.inout(), _ob_in);
                }
                catch(const ::CORBA::SystemException& _ob_ex)
                {
                    _OB_unmarshalEx(_ob_down, _ob_ex);
                }
                _OB_postUnmarshal(_ob_down);
                return _ob_r._retn();
            }
        }
        catch(const OB::FailureException& _ob_ex)
        {
            _OB_handleFailureException(_ob_down, _ob_ex);
        }
    }
}
